#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls='ls --color=auto'
alias dmesg='dmesg --human'
alias nano='nano -w -T 2 -m'
alias y='yaourt'
alias p='sudo pacman'

#PS1='[\u@\h \W]\$ '
PS1='\[\e[32;1m\]\u\[\e[37;1m\]@\[\e[31;1m\]\H \[\e[0m\]\W>'

PATH=$HOME/x-tools7h/arm-cubieboard-linux-gnueabi/bin/:$PATH
