default:
		
ctconfig:
	ct-ng -C cross/ menuconfig
ctbuild:
	ct-ng -C cross/ build
ctcleancross:
	rm -rf cross/
	mkdir -p $HOME/cross/src
ctcleanxtools:
	rm -rf x-tools7h/
kernelconfig:
	make -C linux-sunxi/ ARCH=arm menuconfig
kernelbuild:
	make -C linux-sunxi/ ARCH=arm CROSS_COMPILE=arm-cubieboard-linux-gnueabi- uImage modules
